services:
  drivenopsdb:
    image: postgres
    container_name: drivenopsdb
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env.test
    volumes:
      - pg:/var/lib/postgresql/data

  node_app_github-ci:
    container_name: node_app_github-ci
    build: ./back-end/.
    ports:
      - 5000:5000
    depends_on:
      - drivenopsdb
    env_file:
      - back-end/.env.test

  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - nginx_react:/var/www/html
    
  nginx_server:
    container_name: nginx_server
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - nginx_react:/var/www/html
    depends_on:
      - drivenopsdb
      - node_app_github-ci
      - react_app

volumes:
  pg:
  nginx_react: