services:
  drivenopsdb:
    image: postgres
    container_name: drivenopsdb
    restart: always
    ports:
      - 5566:5432
    env_file:
      - back-end/.env.test
      

  node_app_github-ci:
    container_name: node_app_github-ci
    build: .
    ports:
      - 5000:5000
    depends_on:
      - drivenopsdb
    env_file:
      - back-end/.env.test
