version: "3"
services:
  drivenopsdb:
    image: postgres
    container_name: drivenopsdb
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env.test

  node_app:
    container_name: node_app_github-ci
    build: ./back-end/.
    ports:
      - 5000:5000
    env_file:
      - back-end/.env.test
    depends_on:
      - drivenopsdb